version: '3.4'
services:
  server:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    links:
      - postgres
    restart: always
  postgres:
    image: postgres:9.6.6-alpine
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'